### ISSUE TITLE
MultisigIsm config incorrectly parses the set of validators

### ISSUE THREAD

**Issue by serejke** [hyperlane-xyz/hyperlane-deploy#31]
I have a config at `config/multisig_ism.json` as:
```
"ethereum1": {
    "threshold": 2,
    "validators": [
      {
        "address": "0x1CBd3b2770909D4e10f157cABC84C7264073C9Ec",
        "name": "validator 1"
      },
      {
        "address": "0xdF3e18d64BC6A983f673Ab319CCaE4f1a57C7097",
        "name": "validator 2"
      },
      {
        "address": "0xcd3B766CCDd6AE721141F452C550Ca635964ce71",
        "name": "validator 3"
      }
    ]
  },
```

above only 3 validators are specified. But `Multisig.validators` returns 5 validators:
```
  0x0000000000000000000000000000000000000020
  0x0000000000000000000000000000000000000003
  0x1CBd3b2770909D4e10f157cABC84C7264073C9Ec
  0xdF3e18d64BC6A983f673Ab319CCaE4f1a57C7097
  0xcd3B766CCDd6AE721141F452C550Ca635964ce71
```

This is because the `readMultisigIsmDomainConfig` uses JSON `parseRaw` on `.validators[*].address` that returns ABI-encoded byte array (including the offset specifier and length).

https://github.com/hyperlane-xyz/hyperlane-deploy/blob/28af30d0d99e9a4ff31751742ea069eec70b026a/lib/ConfigLib.sol#L122
https://github.com/hyperlane-xyz/hyperlane-deploy/blob/28af30d0d99e9a4ff31751742ea069eec70b026a/lib/ConfigLib.sol#L123

One workaround I applied locally was to read addresses starting from that offset:
```
        uint256 offset = 64;
        uint256 numValidators = (validatorBytes.length - offset) / 32;
        address[] memory validators = new address[](numValidators);
        for (uint256 i = 0; i < validators.length; i++) {
            validators[i] = abi.decode(
                validatorBytes.slice(offset + i * 32, 32),
                (address)
            );
        }
```

There must be a better way. I experimented with `StdJson.sol`'s utility function
```
address[] memory validators = json.readAddressArray(
   string.concat(".", chainName, ".validators[*].address")
);
```

but it doesn't work with wildcard `*` selector.

**Comment by nambrot** [comment]
Thanks for filing (as well as your scraper PR!) @serejke. Are you in our Discord btw?

**Comment by serejke** [comment]
@nambrot just joined! `serejke#5191`
