### ISSUE TITLE
Contracts' `owner` is equal to deployer, and cannot be configured (new TS SDK)

### ISSUE THREAD

**Issue by serejke** [hyperlane-xyz/hyperlane-deploy#52]
It's probably a minor change in the new TypeScript SDK, but previously with Forge scripting it was possible to set a different `owner` (in [`config/networks.json`](https://github.com/hyperlane-xyz/hyperlane-deploy/commit/b839529296a5cf0e968c17e95e03f68c8b89da3c#diff-c874f625e511d9ba8cb68cb1bdddf0ca4f976b150fa0882ab24cc6f5ffcac3d1R4)) than the deployer key,

now the owner is always the deployer:
https://github.com/hyperlane-xyz/hyperlane-deploy/blob/97b7e87f572b05dee231d1f547b8e69ede9c125b/src/core/HyperlanePermissionlessDeployer.ts#L125

We want to transfer ownership of the deployed contracts to a Safe wallet. So using the new SDK we need to call `transferOwnership` on all the deployed contracts, which means an additional post-deployment step

**Comment by distributedstatemachine** [comment]
Good catch. can we open against the hyperlane repo stating that we would prefer the former behaviour?

**Comment by distributedstatemachine** [comment]
wrong repo. pt 2

**Comment by asaj** [comment]
@serejke good suggestion, I can add a flag

**Comment by nambrot** [comment]
@serejke I'm not sure if we are able to get to this very soon, so if you are blocked by this I'd recommend  maybe working on this yourself

**Comment by serejke** [comment]
@nambrot we're using the old school Forge `hyperlane-deploy` scripts (customized for us) for now, and will migrate to TypeScript SDK a bit later. Will be happy to open a PR then
