### ISSUE TITLE
Add Interchain contracts to deploy script

### ISSUE THREAD

**Issue by HariSeldon23** [hyperlane-xyz/hyperlane-deploy#56]
Currently the following contracts are not included in the deployment script:
*  interchainQueryRouter
* interchainAccountRouter
* interchainAccountIsm
* aggregationIsmFactory
* routingIsmFactory

Happy submitting a PR if I get the thumbs up?

**Comment by nambrot** [comment]
Of course! Are you in our discord? Happy to chat more about it

**Comment by HariSeldon23** [comment]
Yup, I'm in the Discord `Trollip | Pangolin#4506`
